apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterFederatedTrustDomain
metadata:
  name: cluster2.demo
spec:
  trustDomain: cluster2.demo
  bundleEndpointURL: <replace with ip of spire server endpoint on cluster 2 e.g. https://172.16.17.3:8443>
  bundleEndpointProfile:
    type: https_spiffe
    endpointSPIFFEID: spiffe://cluster2.demo/spire/server
  trustDomainBundle: |-
    {
      <add trust bundle keys from cluster 2 e.g. 
      "keys": [
            {
                "use": "x509-svid",
                "kty": "EC",
                "crv": "P-256",.......>
    }
